# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "web"

scrape_configs:
  - job_name: "prometheus"

    static_configs:
      - targets: [ "localhost:9090" ]

  - job_name: "web"
    dns_sd_configs:
      - names: [ "web" ]
        port: 8001
        type: A
        refresh_interval: 5s
